
interface _GlobalComponents {
      'IconsCalender': typeof import("../components/Icons/Calender.vue")['default']
    'IconsFriends': typeof import("../components/Icons/Friends.vue")['default']
    'IconsMessage': typeof import("../components/Icons/Message.vue")['default']
    'IconsNotification': typeof import("../components/Icons/Notification.vue")['default']
    'IconsProfile': typeof import("../components/Icons/Profile.vue")['default']
    'LoaderCircle': typeof import("../components/Loader/Circle.vue")['default']
    'LoaderImgTake': typeof import("../components/Loader/ImgTake.vue")['default']
    'LoaderUniversal': typeof import("../components/Loader/Universal.vue")['default']
    'ModalContainer': typeof import("../components/Modal/Container.vue")['default']
    'ModalDelete': typeof import("../components/Modal/Delete.vue")['default']
    'ModalFilter': typeof import("../components/Modal/Filter.vue")['default']
    'ModalPhotoviewer': typeof import("../components/Modal/Photoviewer.vue")['default']
    'ModalRegistrationContainer': typeof import("../components/Modal/RegistrationContainer.vue")['default']
    'PanelBottom': typeof import("../components/Panel/Bottom.vue")['default']
    'ProductsColors copy': typeof import("../components/Products/Sizes.vue")['default']
    'ProductsColors': typeof import("../components/Products/Colors.vue")['default']
    'ProductsDetails': typeof import("../components/Products/Details.vue")['default']
    'SkeletonAbout': typeof import("../components/Skeleton/About.vue")['default']
    'SkeletonCards': typeof import("../components/Skeleton/Cards.vue")['default']
    'SkeletonEventImg': typeof import("../components/Skeleton/EventImg.vue")['default']
    'SkeletonFriends': typeof import("../components/Skeleton/Friends.vue")['default']
    'SkeletonInterests': typeof import("../components/Skeleton/Interests.vue")['default']
    'SkeletonMsgBox': typeof import("../components/Skeleton/MsgBox.vue")['default']
    'SkeletonMsgGroupCards': typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
    'SkeletonName': typeof import("../components/Skeleton/Name.vue")['default']
    'SkeletonParticipants': typeof import("../components/Skeleton/Participants.vue")['default']
    'SkeletonParticipantsAndDelete': typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
    'SkeletonPhotos': typeof import("../components/Skeleton/Photos.vue")['default']
    'SkeletonProfileImg': typeof import("../components/Skeleton/ProfileImg.vue")['default']
    'SkeletonSlider': typeof import("../components/Skeleton/Slider.vue")['default']
    'SkeletonSpinner': typeof import("../components/Skeleton/Spinner.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyIconsCalender': typeof import("../components/Icons/Calender.vue")['default']
    'LazyIconsFriends': typeof import("../components/Icons/Friends.vue")['default']
    'LazyIconsMessage': typeof import("../components/Icons/Message.vue")['default']
    'LazyIconsNotification': typeof import("../components/Icons/Notification.vue")['default']
    'LazyIconsProfile': typeof import("../components/Icons/Profile.vue")['default']
    'LazyLoaderCircle': typeof import("../components/Loader/Circle.vue")['default']
    'LazyLoaderImgTake': typeof import("../components/Loader/ImgTake.vue")['default']
    'LazyLoaderUniversal': typeof import("../components/Loader/Universal.vue")['default']
    'LazyModalContainer': typeof import("../components/Modal/Container.vue")['default']
    'LazyModalDelete': typeof import("../components/Modal/Delete.vue")['default']
    'LazyModalFilter': typeof import("../components/Modal/Filter.vue")['default']
    'LazyModalPhotoviewer': typeof import("../components/Modal/Photoviewer.vue")['default']
    'LazyModalRegistrationContainer': typeof import("../components/Modal/RegistrationContainer.vue")['default']
    'LazyPanelBottom': typeof import("../components/Panel/Bottom.vue")['default']
    'LazyProductsColors copy': typeof import("../components/Products/Sizes.vue")['default']
    'LazyProductsColors': typeof import("../components/Products/Colors.vue")['default']
    'LazyProductsDetails': typeof import("../components/Products/Details.vue")['default']
    'LazySkeletonAbout': typeof import("../components/Skeleton/About.vue")['default']
    'LazySkeletonCards': typeof import("../components/Skeleton/Cards.vue")['default']
    'LazySkeletonEventImg': typeof import("../components/Skeleton/EventImg.vue")['default']
    'LazySkeletonFriends': typeof import("../components/Skeleton/Friends.vue")['default']
    'LazySkeletonInterests': typeof import("../components/Skeleton/Interests.vue")['default']
    'LazySkeletonMsgBox': typeof import("../components/Skeleton/MsgBox.vue")['default']
    'LazySkeletonMsgGroupCards': typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
    'LazySkeletonName': typeof import("../components/Skeleton/Name.vue")['default']
    'LazySkeletonParticipants': typeof import("../components/Skeleton/Participants.vue")['default']
    'LazySkeletonParticipantsAndDelete': typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
    'LazySkeletonPhotos': typeof import("../components/Skeleton/Photos.vue")['default']
    'LazySkeletonProfileImg': typeof import("../components/Skeleton/ProfileImg.vue")['default']
    'LazySkeletonSlider': typeof import("../components/Skeleton/Slider.vue")['default']
    'LazySkeletonSpinner': typeof import("../components/Skeleton/Spinner.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const IconsCalender: typeof import("../components/Icons/Calender.vue")['default']
export const IconsFriends: typeof import("../components/Icons/Friends.vue")['default']
export const IconsMessage: typeof import("../components/Icons/Message.vue")['default']
export const IconsNotification: typeof import("../components/Icons/Notification.vue")['default']
export const IconsProfile: typeof import("../components/Icons/Profile.vue")['default']
export const LoaderCircle: typeof import("../components/Loader/Circle.vue")['default']
export const LoaderImgTake: typeof import("../components/Loader/ImgTake.vue")['default']
export const LoaderUniversal: typeof import("../components/Loader/Universal.vue")['default']
export const ModalContainer: typeof import("../components/Modal/Container.vue")['default']
export const ModalDelete: typeof import("../components/Modal/Delete.vue")['default']
export const ModalFilter: typeof import("../components/Modal/Filter.vue")['default']
export const ModalPhotoviewer: typeof import("../components/Modal/Photoviewer.vue")['default']
export const ModalRegistrationContainer: typeof import("../components/Modal/RegistrationContainer.vue")['default']
export const PanelBottom: typeof import("../components/Panel/Bottom.vue")['default']
export const ProductsColors copy: typeof import("../components/Products/Sizes.vue")['default']
export const ProductsColors: typeof import("../components/Products/Colors.vue")['default']
export const ProductsDetails: typeof import("../components/Products/Details.vue")['default']
export const SkeletonAbout: typeof import("../components/Skeleton/About.vue")['default']
export const SkeletonCards: typeof import("../components/Skeleton/Cards.vue")['default']
export const SkeletonEventImg: typeof import("../components/Skeleton/EventImg.vue")['default']
export const SkeletonFriends: typeof import("../components/Skeleton/Friends.vue")['default']
export const SkeletonInterests: typeof import("../components/Skeleton/Interests.vue")['default']
export const SkeletonMsgBox: typeof import("../components/Skeleton/MsgBox.vue")['default']
export const SkeletonMsgGroupCards: typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
export const SkeletonName: typeof import("../components/Skeleton/Name.vue")['default']
export const SkeletonParticipants: typeof import("../components/Skeleton/Participants.vue")['default']
export const SkeletonParticipantsAndDelete: typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
export const SkeletonPhotos: typeof import("../components/Skeleton/Photos.vue")['default']
export const SkeletonProfileImg: typeof import("../components/Skeleton/ProfileImg.vue")['default']
export const SkeletonSlider: typeof import("../components/Skeleton/Slider.vue")['default']
export const SkeletonSpinner: typeof import("../components/Skeleton/Spinner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyIconsCalender: typeof import("../components/Icons/Calender.vue")['default']
export const LazyIconsFriends: typeof import("../components/Icons/Friends.vue")['default']
export const LazyIconsMessage: typeof import("../components/Icons/Message.vue")['default']
export const LazyIconsNotification: typeof import("../components/Icons/Notification.vue")['default']
export const LazyIconsProfile: typeof import("../components/Icons/Profile.vue")['default']
export const LazyLoaderCircle: typeof import("../components/Loader/Circle.vue")['default']
export const LazyLoaderImgTake: typeof import("../components/Loader/ImgTake.vue")['default']
export const LazyLoaderUniversal: typeof import("../components/Loader/Universal.vue")['default']
export const LazyModalContainer: typeof import("../components/Modal/Container.vue")['default']
export const LazyModalDelete: typeof import("../components/Modal/Delete.vue")['default']
export const LazyModalFilter: typeof import("../components/Modal/Filter.vue")['default']
export const LazyModalPhotoviewer: typeof import("../components/Modal/Photoviewer.vue")['default']
export const LazyModalRegistrationContainer: typeof import("../components/Modal/RegistrationContainer.vue")['default']
export const LazyPanelBottom: typeof import("../components/Panel/Bottom.vue")['default']
export const LazyProductsColors copy: typeof import("../components/Products/Sizes.vue")['default']
export const LazyProductsColors: typeof import("../components/Products/Colors.vue")['default']
export const LazyProductsDetails: typeof import("../components/Products/Details.vue")['default']
export const LazySkeletonAbout: typeof import("../components/Skeleton/About.vue")['default']
export const LazySkeletonCards: typeof import("../components/Skeleton/Cards.vue")['default']
export const LazySkeletonEventImg: typeof import("../components/Skeleton/EventImg.vue")['default']
export const LazySkeletonFriends: typeof import("../components/Skeleton/Friends.vue")['default']
export const LazySkeletonInterests: typeof import("../components/Skeleton/Interests.vue")['default']
export const LazySkeletonMsgBox: typeof import("../components/Skeleton/MsgBox.vue")['default']
export const LazySkeletonMsgGroupCards: typeof import("../components/Skeleton/MsgGroupCards.vue")['default']
export const LazySkeletonName: typeof import("../components/Skeleton/Name.vue")['default']
export const LazySkeletonParticipants: typeof import("../components/Skeleton/Participants.vue")['default']
export const LazySkeletonParticipantsAndDelete: typeof import("../components/Skeleton/ParticipantsAndDelete.vue")['default']
export const LazySkeletonPhotos: typeof import("../components/Skeleton/Photos.vue")['default']
export const LazySkeletonProfileImg: typeof import("../components/Skeleton/ProfileImg.vue")['default']
export const LazySkeletonSlider: typeof import("../components/Skeleton/Slider.vue")['default']
export const LazySkeletonSpinner: typeof import("../components/Skeleton/Spinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
