// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/14/2024, 11:39:52 AM
const configMerger = require("D:/Web Development/job/softnio/softnio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Web Development/job/softnio/softnio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/plugins/**/*.{js,ts,mjs}","D:/Web Development/job/softnio/softnio/composables/**/*.{js,ts,mjs}","D:/Web Development/job/softnio/softnio/utils/**/*.{js,ts,mjs}","D:/Web Development/job/softnio/softnio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Web Development/job/softnio/softnio/app.config.{js,ts,mjs}"] }));

module.exports = config
